apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qwe-qwe-poi-gateway-app-dev
  annotations:
    argocd/app-name: qwe-qwe-poi-gateway-app-dev
    backstage.io/kubernetes-id: qwe-qwe-poi-gateway-app-dev
    backstage.io/kubernetes-namespace: qwe
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=qwe-qwe-poi-gateway-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/qwe-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/qwe/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/qwe/deployments/qwe-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/qwe-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/q30000"
  system: workshop-system-qwe
  providesApis:
    - gateway-api-qwe
  consumesApis:
    - backend-api-qwe
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-qwe
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/q30000"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-qwe
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://qwe-poi-gateway-app-qwe.apps.summit23rock.n26o.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23Janus1/qwe-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/q30000"
  system: workshop-system-qwe
  definition:
    $text: https://github.com/Summit23Janus1/qwe-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
